server:
  port : 8091
spring:
  application:
    name: "@project.name@"
  flyway:
    url: jdbc:mysql://localhost:3306/mysql
    user: root
    password: docker
    schemas: marketplace-product
    locations: classpath:db/migration
  datasource:
    url: jdbc:mysql://localhost:3306/marketplace-product
    username: root
    password: docker
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: false
    hibernate:
      ddl-auto: validate